Repository Gaming32/ArrayV, pull requests merged in 2021-02, with the labels that each got.

#6 New Sorting Algorithms
  src/sorts/concurrent/MergeExchangeSort.java
  src/sorts/exchange/FunSort.java
  src/sorts/exchange/StableStoogeSort.java
  src/sorts/hybrid/StupidQuickSort.java
  src/sorts/insert/FibonacciInsertionSort.java
  src/sorts/insert/SplaySort.java
  src/sorts/select/StableSelectionSort.java
Labels: enhancement

#8 Add OutOfPlaceWeaveMerge to ArrayV
  src/sorts/merge/OutOfPlaceWeaveMerge.java
Labels: enhancement, good first issue

#13 Mode selector
  src/frames/UtilFrame.java
  src/main/ArrayManager.java
  src/main/ArrayVisualizer.java
  src/prompts/SortPrompt.java
  src/sorts/exchange/ooPQuicksort.java
  src/sorts/templates/MergeSorting.java
  src/threads/RunComparisonSort.java
  src/utils/AntiQSort.java
  src/utils/Reads.java
Labels: enhancement, new-feature
