Repository Gaming32/ArrayV, pull requests merged in 2021-05, with the labels that each got.

#37 Apollyon's Bitonic Sort
  src/sorts/exchange/ApollyonSort.java
Labels: enhancement, new-sorts

#53 Sorting networks changes
  src/frames/UtilFrame.java
  src/sorts/concurrent/ApollyonSort.java
  src/sorts/concurrent/BitonicSortRecursive.java
  src/sorts/concurrent/BoseNelsonSortParallel.java
  src/sorts/concurrent/BoseNelsonSortRecursive.java
  src/sorts/concurrent/OddEvenMergeSortRecursive.java
  src/sorts/concurrent/PairwiseSortIterative.java
  src/sorts/concurrent/PairwiseSortRecursive.java
  src/sorts/exchange/AwkwardSort.java
  src/sorts/exchange/GnomeSort.java
  src/sorts/exchange/SlopeSort.java
  src/utils/SortingNetworkGenerator.java
Labels: enhancement, improved-feature

#52 Sorting networks
  .gitignore
  src/frames/UtilFrame.java
  src/main/ArrayVisualizer.java
  src/resources/sorting_network_master/.gitignore
  src/resources/sorting_network_master/LICENSE
  src/resources/sorting_network_master/README.md
  src/resources/sorting_network_master/SortingNetworkFetcher.java
  src/resources/sorting_network_master/examples/16-input.cn
  src/resources/sorting_network_master/examples/16-input.png
  src/resources/sorting_network_master/examples/16-input.svg
  src/resources/sorting_network_master/examples/4-input.cn
  src/resources/sorting_network_master/examples/4-input.png
  src/resources/sorting_network_master/examples/4-input.svg
  src/resources/sorting_network_master/examples/5-input.cn
  src/resources/sorting_network_master/examples/5-input.png
  src/resources/sorting_network_master/examples/5-input.svg
  src/resources/sorting_network_master/out.svg
  src/resources/sorting_network_master/sortingnetwork.py
  src/sorts/concurrent/ApollyonSort.java
  src/sorts/concurrent/BitonicSortRecursive.java
  src/sorts/concurrent/BoseNelsonSortParallel.java
  src/sorts/concurrent/BoseNelsonSortRecursive.java
  src/sorts/concurrent/OddEvenMergeSortRecursive.java
  src/sorts/concurrent/PairwiseSortIterative.java
  src/sorts/concurrent/PairwiseSortRecursive.java
  src/sorts/exchange/AwkwardSort.java
  src/sorts/exchange/GnomeSort.java
  src/sorts/exchange/SlopeSort.java
  src/threads/RunComparisonSort.java
  src/utils/Reads.java
  src/utils/SortingNetworkGenerator.java
Labels: enhancement, new-feature
